# Generated by Django 3.2.6 on 2021-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryeaisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
