# Generated by Django 3.2.8 on 2021-10-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tryeaisapp', '0002_auto_20211028_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('budget', models.DecimalField(decimal_places=4, max_digits=10)),
                ('photo', models.ImageField(upload_to='')),
                ('daily_reminder', models.BooleanField(default=False)),
                ('weekly_reminder', models.BooleanField(default=False)),
                ('monthly_reminder', models.BooleanField(default=False)),
                ('yearly_reminder', models.BooleanField(default=False)),
                ('daily_report', models.BooleanField(default=False)),
                ('weekly_report', models.BooleanField(default=False)),
                ('monthly_report', models.BooleanField(default=False)),
                ('yearly_report', models.BooleanField(default=False)),
            ],
        ),
    ]
